apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieticketbookingplatform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movieticketbookingplatform
  template:
    metadata:
      labels:
        app: movieticketbookingplatform
    spec:
      containers:
        - name: movieticketbookingplatform
          image: movieticketbookingplatform:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/moviedb
            - name: SPRING_DATASOURCE_USERNAME
              value: <username>
            - name: SPRING_DATASOURCE_PASSWORD
              value: <password>
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://localhost:27017/moviedb
            - name: SPRING_REDIS_HOST
              value: localhost
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: localhost:9092