apiVersion: v1
kind: Service
metadata:
  name: movieticketbookingplatform
spec:
  selector:
    app: movieticketbookingplatform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer